//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GothamSubway.Importer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FootTraffic
    {
        public int FootTrafficId { get; set; }
        public System.DateTime Date { get; set; }
        public int StationId { get; set; }
        public int TransferId { get; set; }
        public int BeforeSix { get; set; }
        public int SixToSeven { get; set; }
        public int SevenToEight { get; set; }
        public int EightToNine { get; set; }
        public int NineToTen { get; set; }
        public int TenToEleven { get; set; }
        public int ElevenToTwelve { get; set; }
        public int TwelveToThirteen { get; set; }
        public int ThirteenToFourteen { get; set; }
        public int FourteenToFifteen { get; set; }
        public int FifteenToSixteen { get; set; }
        public int SixteenToSeventeen { get; set; }
        public int SeventeenToEighteen { get; set; }
        public int EighteenToNineteen { get; set; }
        public int NineteenToTwenty { get; set; }
        public int TwentyToTwentyOne { get; set; }
        public int TwnetyOneToTwentyTwo { get; set; }
        public int TwentyTwoToTwentyThree { get; set; }
        public int TwentyThreeToTwentyFour { get; set; }
        public int AfterTwentyFour { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual Transfer Transfer { get; set; }
    }
}
