//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GothamSubway.Importer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisfactionCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SatisfactionCategory()
        {
            this.Satisfactions = new HashSet<Satisfaction>();
            this.SatisfactionCategory1 = new HashSet<SatisfactionCategory>();
        }
    
        public int SatisfactionCategoryId { get; set; }
        public Nullable<int> UpperId { get; set; }
        public string Item { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satisfaction> Satisfactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisfactionCategory> SatisfactionCategory1 { get; set; }
        public virtual SatisfactionCategory SatisfactionCategory2 { get; set; }
    }
}
